---
title: "PS270 Final Project"
author: Taylor D'Andrea
description: "Incarceration Trends Across American Cities"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

I am interested in exploring data related to incarceration trends in the United States. Over the course of American history, Criminal Justice policies have changed drastically and incarceration has increasingly accelerated. In my analysis, I'd like to conduct an analysis of the "who" and "why" of modern incarceration trends. 

## The Proposal
Does the urbanicity, in conjunction with gender and racial composition, bolster incarceration rates across America counties? In this study, I plan to analyze the extent to which living in an American urban center, across gender and racial lines, enhances the incarceration rates in that particular place. I hypothesize that the more urban the county, the greater the incarceration rate will be. And I expect this increase will carry across all genders and races, though I do predict a disproportionately higher rate of incarceration for men over women, as well as for Black, Latinx and Native American individuals over Whites. Much research in the fields of Criminal Justice and Sociology have found patterns of increased incarceration for American cities, American ethnic centers, as opposed to suburban or rural areas of the country. The more economically diverse, ethnically diverse, opportunity diverse a place, the increased likelihood there is for conflict and the potential for incarceration. The data sample I will be using to conduct this analysis is comprised of American incarceration trends between 1983 and 2016. The data for this research came from the National Corrections Reporting Program (NCRP), the Deaths in Custody Reporting Program (DCRP), the Annual Survey of Jails (ASJ), the Census of Jails (COJ), the Census of State and Federal Adult Correctional Facilities (CAF), the FBI Uniform Crime Reporting Program (UCR), the Centers on Disease Control (CDC) - the National Vital Statistics System Data -, the U.S. Department of Agriculture, and the U.S. Census Bureau. My unit of analysis is the American prison system. The explanatory variables of interest are "urbanicity" which is rated on a scale of rural, small/mid, suburban, and urban. The co-explanatory variables will be gender (male or female) and race (White, Black, Latinx, or Native American). The outcome variable will be the incarceration rate (incarcerated individuals in a country per un-incarcerated individual) of American counties, which will be studied according to their determined urbanicity rating. The incarceration rate will also be studied for different combinations of gender and race in urban, versus small/mid, suburban and rural American communities. My hypothesis will be proven correct if urban centers have higher incarceration rates than small/mid, suburban, or rural counties and if those rates are disproportionately higher for men and Black, Latinx, and Native American members of those communities. My hypothesis would be disproven if the incarceration rate for urban centers is not different or less than that of urban counties in the United States. My hypothesis would also be disproven if gender and/or race have the opposite or no effect on the incarceration rates I have predicted. 
